In [8]:
import numpy as np
import torch
path = "/home/tangexing/tgx/models/Llama-2-7b-hf-offload/Llama-2-7b-hf-np/layers.27.self_attn.rotary_emb.inv_freq"
path2 = "/home/tangexing/tgx/models/Llama-2-7b-hf-offload/Llama-2-7b-hf-np/layers.28.self_attn.rotary_emb.inv_freq"

print(torch.from_numpy(np.load(path)))
print(torch.from_numpy(np.load(path2)))
inv_freq = 1.0 / (10000 ** (torch.arange(0, 128, 2, dtype=torch.int64).float() / 128))
print(inv_freq)

tensor([1.0000e+00, 8.6572e-01, 7.5000e-01, 6.4941e-01, 5.6250e-01, 4.8706e-01,
        4.2163e-01, 3.6523e-01, 3.1616e-01, 2.7393e-01, 2.3718e-01, 2.0532e-01,
        1.7786e-01, 1.5405e-01, 1.3330e-01, 1.1548e-01, 9.9976e-02, 8.6609e-02,
        7.5012e-02, 6.4941e-02, 5.6244e-02, 4.8706e-02, 4.2175e-02, 3.6530e-02,
        3.1616e-02, 2.7390e-02, 2.3712e-02, 2.0538e-02, 1.7776e-02, 1.5396e-02,
        1.3336e-02, 1.1551e-02, 1.0002e-02, 8.6594e-03, 7.4997e-03, 6.4926e-03,
        5.6229e-03, 4.8714e-03, 4.2152e-03, 3.6526e-03, 3.1624e-03, 2.7390e-03,
        2.3708e-03, 2.0542e-03, 1.7786e-03, 1.5402e-03, 1.3332e-03, 1.1549e-03,
        1.0004e-03, 8.6594e-04, 7.5006e-04, 6.4945e-04, 5.6219e-04, 4.8685e-04,
        4.2176e-04, 3.6526e-04, 3.1614e-04, 2.7394e-04, 2.3711e-04, 2.0540e-04,
        1.7786e-04, 1.5402e-04, 1.3340e-04, 1.1545e-04])
tensor([1.0000e+00, 8.6572e-01, 7.5000e-01, 6.4941e-01, 5.6250e-01, 4.8706e-01,
        4.2163e-01, 3.6523e-01, 3.1616e-01, 2.7393e-01, 2.3718e

In [13]:
a = torch.tensor([0, 1, 2, 3, 4])
b = torch.tensor([1, 2, 3])
ls = [a, b]
c, d = ls 
c 

tensor([0, 1, 2, 3, 4])

In [11]:
path = "/home/tangexing/tgx/models/Llama-2-7b-hf-offload/Llama-2-7b-hf-np/layers.27.mlp.up_proj.weight"
print(torch.from_numpy(np.load(path)).shape)

torch.Size([11008, 4096])
